sudo: false
language: go
go:
  - 1.8
  - 1.7
  - master

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email:
    recipients:
    - oliver@weyhmueller.de
    on_success: never
    on_failure: change
